auth_1:
  api_key: YOUR API KEY1
  proxy: http://127.0.0.1:51217
  requests_per_min: 10
  tokens_per_min: 40000

auth_2:
  api_key: YOUR API KEY2
  proxy: http://127.0.0.1:51217
  requests_per_min: 10
  tokens_per_min: 40000
